// This file is generated by scripts/generate-audit-status-content.mjs.
// Edit the canonical Markdown files in docs/audit-status-content and regenerate.

import type { ScoringCheckId } from "@/lib/scoring/check-registry";

export type AuditCheckStatus = "passed" | "needs_review" | "failed";

export type AuditCheckStatusContent = {
  details: string;
  recommendation: string;
};

export const CHECK_STATUS_CONTENT = {
  "brand.author_name": {
    passed: {
      details: "The scan found the author name presented clearly in the website content or identity signals.",
      recommendation: "Keep the published author name as selectable text in the site header or hero, include it in the homepage `<title>` and primary H1, and keep Person schema naming consistent. Recheck these fields after theme, template, or SEO-plugin changes so the identity signal remains available on desktop and mobile.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the rendered homepage, document `<title>`, primary H1, header text, and Person schema to confirm that the published author name is exposed as text. If the name appears only inside an image, slider, or interaction-dependent component, add an accessible text equivalent or make that component available to the scanner before rescanning.",
    },
    failed: {
      details: "The scan did not find a clear author name in the page title, main heading, or structured data.",
      recommendation: "Add the published author name as selectable text in the homepage H1 or hero and include the same canonical name in the `<title>` and Person schema. Keep spelling and pen-name formatting consistent, and verify that the name remains visible in the mobile header or initial viewport.",
    },
  },
  "brand.genre_positioning": {
    passed: {
      details: "The scan found wording that communicates the author's genre or writing category.",
      recommendation: "Keep the primary genre or writing category in visible homepage copy near the author introduction, and use the same terminology in relevant metadata where natural. Review the wording whenever the author changes genre focus, pen name positioning, or target readership.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Review the visible homepage introduction and headings for a plain-language genre or writing-category phrase. If the wording is loaded only after interaction or embedded in artwork, expose it as rendered HTML text and rerun the scan.",
    },
    failed: {
      details: "The scan did not find clear genre, topic, or writing category language.",
      recommendation: "Add a plain-language genre or writing-category phrase near the author name or homepage introduction, such as “historical romance author.” Use the same primary category consistently in relevant headings and metadata without keyword stuffing.",
    },
  },
  "brand.homepage_headline": {
    passed: {
      details: "The homepage includes a headline that gives visitors useful author-brand context.",
      recommendation: "Retain one dominant homepage headline that identifies the author, books, genre, or reader promise without competing hero messages. After redesigning the hero or adding promotional banners, confirm that the headline remains the primary H1 and is visible before interaction.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the homepage in a signed-out browser and verify that one prominent headline identifies the author, books, genre, or reader promise. Confirm that the headline exists in the rendered DOM and is not hidden behind a carousel, popup, or consent layer before rescanning.",
    },
    failed: {
      details: "The homepage did not provide a clear headline that quickly orients readers.",
      recommendation: "Replace vague or competing hero slogans with one primary H1 that identifies the author, the type of books, or a specific reader promise. Render it as visible HTML text above the fold and keep secondary promotional messages at lower heading levels.",
    },
  },
  "brand.about_path": {
    passed: {
      details: "The scan found an About page, author biography section, or a clear path to author information.",
      recommendation: "Keep the About page linked with a standard crawlable `<a href>` from the main navigation or homepage, and return a direct successful response from the destination URL. Review the biography and link target after permalink, menu, or site-structure changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Follow the About path from the homepage and primary navigation, confirm that the destination returns a direct successful HTML response, and verify that the biography is visible without login. If the page is unlinked, redirected excessively, or blocked from crawling, correct that access path and rerun the scan.",
    },
    failed: {
      details: "The scan did not find an About page, author bio path, or clear About section.",
      recommendation: "Create a public About page with a concise biography and link to it using standard anchors from the primary navigation, homepage, and footer. Ensure the URL returns a direct successful HTML response and is not blocked from crawling.",
    },
  },
  "brand.homepage_content_depth": {
    passed: {
      details: "The homepage contains enough introductory text to give readers useful context about the author or books.",
      recommendation: "Maintain a short, readable homepage introduction in the rendered page content that explains who the author is, what they write, and the next reader step. Avoid moving the only introduction into an image, slider, popup, or content that appears only after interaction.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the initial rendered homepage for a readable introduction that explains the author or books. If the only context is inside images, sliders, or content injected after user interaction, add a short HTML introduction that the scanner and assistive technology can read.",
    },
    failed: {
      details: "The homepage scan found limited readable content to explain the author brand.",
      recommendation: "Add a concise homepage introduction in readable HTML that explains who the author is, what they write, who the books are for, and the next useful reader step. Place it in the default page content rather than relying on an image, carousel, or popup.",
    },
  },
  "books.cover_visibility": {
    passed: {
      details: "The scan found a visible book-cover image in the inspected website content.",
      recommendation: "Continue serving at least one current cover as a responsive `<img>` with intrinsic dimensions, appropriate `srcset` values, and descriptive alt text. Check crop, sharpness, and text legibility at common mobile widths whenever cover artwork is replaced.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Verify that a current cover is rendered as a visible image at the inspected viewport and is not deferred until a carousel click or popup opens. Prefer an `<img>` with a valid `src` or `srcset`, intrinsic dimensions, and descriptive alt text, then rescan the public page.",
    },
    failed: {
      details: "The scan did not find an image that looked like a book cover.",
      recommendation: "Display a current priority-book cover as a responsive `<img>` with correct intrinsic dimensions, `srcset` or equivalent responsive delivery, and descriptive alt text. Link it to the matching book page and verify that it is sharp, uncropped, and legible on mobile.",
    },
  },
  "books.title_visibility": {
    passed: {
      details: "The scan found book-title text presented in the inspected website content.",
      recommendation: "Keep each book title as real HTML text, preferably in a semantic heading near its cover, description, and purchase controls. Do not rely on the title printed inside the cover image as the only machine-readable or accessible title.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Confirm that each featured book has its full title in visible HTML text near the cover. If the title exists only inside cover artwork or appears after interaction, add a semantic text heading and rerun the scan.",
    },
    failed: {
      details: "The scan did not find a clear book title in headings or book structured data.",
      recommendation: "Add the complete book title as real text in a semantic heading beside or below the cover. Keep the title, description, and purchase controls grouped in the same book component across desktop and mobile layouts.",
    },
  },
  "books.description": {
    passed: {
      details: "The scan found descriptive copy that explains a book or gives readers a useful story hook.",
      recommendation: "Keep the book hook or synopsis in visible page text close to the matching cover and purchase links. Review the copy after edition or campaign changes so it remains accurate, concise, and associated with the correct book.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Check the public page for a visible hook, blurb, or synopsis associated with at least one featured book. Place the description in rendered HTML rather than an image, inaccessible accordion, or script-dependent fragment, then rescan.",
    },
    failed: {
      details: "The scan did not find a book description, blurb, synopsis, or similar book copy.",
      recommendation: "Add a concise hook or two-to-three-sentence synopsis as visible HTML near each featured book. Explain the central conflict, promise, or reader appeal and position the copy before the primary purchase control.",
    },
  },
  "books.purchase_links": {
    passed: {
      details: "The scan found a visible link or action that can take readers toward purchasing a book.",
      recommendation: "Keep purchase controls as descriptive links or buttons with valid destinations, and associate each one with the correct title and edition. Periodically test final URLs, redirects, regional storefronts, and mobile behavior, especially after retailer or affiliate-link changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Test every visible purchase control and confirm that it is a standard link or accessible button leading to the intended book or retailer page. Replace JavaScript-only click handlers or blocked redirectors with crawlable final URLs where possible, then rerun the scan.",
    },
    failed: {
      details: "The scan did not find clear buy, order, preorder, or purchase links.",
      recommendation: "Add a clearly labeled purchase link or button for each featured book using a valid final URL for the correct edition and format. Test desktop and mobile activation, redirect behavior, regional storefront routing, and accessible link naming.",
    },
  },
  "books.retailer_options": {
    passed: {
      details: "The scan found more than one retailer or purchase destination for readers.",
      recommendation: "Group only current retailer destinations beneath the correct book and use direct, descriptive links for each store. Test edition, format, and regional routing regularly, and remove links that lead to unavailable or incorrect listings.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Verify that at least two currently valid retailer destinations are shown for the same featured book when the edition is distributed to multiple stores. Use direct, crawlable links and ensure regional or affiliate routing does not block the scanner before rescanning.",
    },
    failed: {
      details: "The scan did not find links to more than one common book retailer.",
      recommendation: "Add direct links to every retailer where the same edition is genuinely available and group them beneath the correct book. Do not create unavailable destinations; when a title is intentionally exclusive, document that state or adjust the audit rule rather than presenting false choices.",
    },
  },
  "books.reader_proof": {
    passed: {
      details: "The scan found reader proof such as reviews, praise, endorsements, ratings, or awards.",
      recommendation: "Keep reviews, endorsements, ratings, or awards visibly attributed to a verifiable source and place the strongest proof near the relevant book. Update or remove claims when source pages change, permissions expire, or stronger recent proof becomes available.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect visible review excerpts, endorsements, ratings, and awards and confirm that each includes a recognizable attribution. If proof is injected through a third-party widget or hidden carousel, add a readable HTML version or ensure the widget renders for the scanner.",
    },
    failed: {
      details: "The scan did not find reviews, praise, endorsements, awards, or reader proof.",
      recommendation: "Add two or three credible review excerpts, endorsements, ratings, or awards near the relevant book and identify each source clearly. Use exact supported wording, link to evidence where appropriate, and avoid unattributed or unverifiable claims.",
    },
  },
  "books.featured_book": {
    passed: {
      details: "The scan found a featured-book presentation in the inspected website content.",
      recommendation: "Maintain one clearly structured featured-book section containing the cover, text title, concise hook, and primary purchase path. Update the selected book and associated links whenever the current release or promotional priority changes.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Confirm that one current book is intentionally presented with its cover, text title, hook, and purchase path in the public page content. If these elements are split across sliders, tabs, or interaction-dependent components, expose a complete default view and rerun the scan.",
    },
    failed: {
      details: "The scan did not find a clear featured book, latest release, or available-now section.",
      recommendation: "Create one prominent featured-book section containing the cover, text title, concise hook, and primary purchase path. Render the complete section in the default homepage content and update it when the current release or campaign priority changes.",
    },
  },
  "engagement.newsletter_signup": {
    passed: {
      details: "The scan found a newsletter signup path or an email subscription form.",
      recommendation: "Keep the subscription form connected to the intended mailing-list audience and limit fields to information required for signup. Test validation, consent text, success messaging, confirmation email, and subscriber routing after form or email-platform changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Submit the newsletter form manually with a test address and verify validation, consent, confirmation, and list delivery. Ensure the form or subscription link is available in the public rendered page and not blocked by an inaccessible iframe, popup trigger, or bot challenge.",
    },
    failed: {
      details: "The scan did not find a newsletter, subscribe form, or email signup field.",
      recommendation: "Add an accessible email signup form connected to the intended mailing-list audience and request only necessary subscriber data. Configure validation, consent text, success messaging, confirmation or double opt-in, and automation delivery, then test the full subscriber flow.",
    },
  },
  "engagement.homepage_signup": {
    passed: {
      details: "The scan found a newsletter signup form or clear subscription link on the homepage.",
      recommendation: "Keep a visible newsletter form or descriptive subscription link in the homepage content, with a second opportunity near the footer when appropriate. Verify its placement and usability at mobile widths after layout, popup, or form-builder updates.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the homepage at desktop and mobile widths and confirm that a newsletter form or clearly labeled subscription link is visible without navigating elsewhere. If it appears only after a popup delay or interaction, add a persistent inline signup path and rescan.",
    },
    failed: {
      details: "The scan did not find the newsletter signup on the homepage.",
      recommendation: "Place a persistent newsletter form or clearly labeled subscription link in the homepage content, with an additional compact opportunity near the footer if appropriate. Do not rely solely on a timed popup, and verify that the form is usable on mobile.",
    },
  },
  "engagement.reader_magnet": {
    passed: {
      details: "The scan found a reader incentive such as a sample, bonus scene, free book, or reading guide.",
      recommendation: "Keep the reader-magnet offer, delivery terms, and file or landing-page destination current. Test the complete subscriber flow periodically, including form submission, automation trigger, email delivery, download permissions, and expired-link behavior.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Verify that the page clearly offers a reader incentive and explains what is delivered after signup. Make the offer and delivery path available as readable page content rather than relying only on a popup, image, or email-platform script that the scanner cannot render.",
    },
    failed: {
      details: "The scan did not find a reader magnet such as a free chapter, bonus scene, free book, or sample download.",
      recommendation: "Create a relevant reader magnet such as a sample chapter, bonus scene, short story, or reading guide and describe exactly what subscribers receive. Connect the form to an automated delivery email or secure download, then test permissions, expiry, and delivery.",
    },
  },
  "engagement.subscriber_benefit": {
    passed: {
      details: "The scan found wording that explains what readers receive by subscribing.",
      recommendation: "Keep the subscriber value proposition immediately beside the signup control and state what readers receive in specific language. Update the copy whenever the newsletter cadence, content mix, incentive, or privacy terms change.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Read the copy immediately surrounding the signup control and confirm that it states what subscribers receive and, where appropriate, how often. If the benefit is supplied only through placeholder text, an image, or delayed script, add persistent HTML copy and rerun the scan.",
    },
    failed: {
      details: "The scan did not find clear wording that explains why readers should subscribe.",
      recommendation: "Add one specific sentence beside the signup control explaining the newsletter content, immediate incentive, and realistic frequency where useful. Keep this copy visible outside placeholders so readers and assistive technology can understand the value before submitting.",
    },
  },
  "search.title_tag": {
    passed: {
      details: "The homepage includes a non-empty HTML title tag.",
      recommendation: "Keep one unique, non-empty homepage `<title>` generated consistently in the server-rendered document head. Review the final rendered title after SEO-plugin, theme, routing, or homepage-setting changes to prevent duplication or fallback text.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the final rendered document head or browser tab and confirm that the homepage contains one meaningful `<title>` element. If metadata is added only client-side or omitted from the initial response, configure the framework or SEO system to render it consistently and rescan.",
    },
    failed: {
      details: "The scan did not find a page title tag, which helps browsers and search engines understand the page.",
      recommendation: "Generate one unique homepage `<title>` in the rendered document head, beginning with the published author name and adding concise genre or role context. Configure the CMS or framework so the title is present in the initial response and not overwritten by duplicate templates.",
    },
  },
  "search.author_title_format": {
    passed: {
      details: "The homepage title contains useful author or brand-identifying wording.",
      recommendation: "Keep the published author name near the beginning of the homepage title and add concise genre or author-role context where it improves clarity. Preview the final title at common search-result widths after brand or metadata changes.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Confirm that the homepage title begins with or clearly includes the published author name and useful author or genre context. Review the final rendered `<title>` rather than only the CMS field, because plugins or templates may overwrite it.",
    },
    failed: {
      details: "The homepage title did not clearly include the author name, author role, books, or writing category.",
      recommendation: "Rewrite the homepage title to clearly identify the published author and primary genre or author role, for example `Author Name | Historical Romance Author`. Put the identifying terms near the beginning and remove slogans that do not explain the site.",
    },
  },
  "search.meta_description": {
    passed: {
      details: "The homepage includes a non-empty meta description.",
      recommendation: "Maintain a distinct homepage meta description in the rendered `<head>` that accurately summarizes the author, books, and useful reader action. Recheck it after campaign, featured-book, SEO-plugin, or template changes so stale or duplicate descriptions are not introduced.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the homepage source and rendered head for one distinct non-empty `<meta name=\"description\">`. If it is missing from the server response, duplicated, or overwritten client-side, correct the metadata template and rerun the scan.",
    },
    failed: {
      details: "The scan did not find a meta description for the scanned pages.",
      recommendation: "Add one distinct `<meta name=\"description\">` to the homepage head that summarizes the author, books or genre, and a useful reader action. Render it consistently through the CMS or application metadata layer and avoid duplicate or empty description tags.",
    },
  },
  "search.single_h1": {
    passed: {
      details: "The inspected page has one identifiable main heading without a multiple-H1 conflict.",
      recommendation: "Preserve exactly one page-level H1 for the main topic and use H2–H6 elements in a logical hierarchy for supporting sections. Reinspect the rendered DOM after page-builder or template edits because visually styled text can accidentally introduce missing or duplicate H1 elements.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the rendered heading structure and confirm that the page has exactly one primary H1. If the H1 is missing, duplicated by the theme, or inserted only after interaction, correct the template or page-builder hierarchy and rescan.",
    },
    failed: {
      details: "The scan either did not find an H1 or found multiple H1 headings on a page.",
      recommendation: "Set one page-specific H1 for the homepage's primary topic and change decorative, logo, or repeated H1 elements to appropriate lower levels or non-heading markup. Verify the final rendered hierarchy so H2–H6 sections follow a logical structure.",
    },
  },
  "search.h1_clarity": {
    passed: {
      details: "The main heading includes useful wording that supports author or book clarity.",
      recommendation: "Keep the homepage H1 understandable without relying on surrounding imagery and connect it directly to the author, genre, books, or reader promise. Reevaluate the wording when the hero design or author positioning changes.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Read the visible H1 without relying on images or nearby copy and confirm that it identifies the author, books, genre, or reader promise. If the scanner cannot see it because it is rendered as artwork, pseudo-content, or delayed JavaScript, replace or supplement it with semantic HTML text.",
    },
    failed: {
      details: "The main heading did not clearly connect the page to the author, books, or genre.",
      recommendation: "Rewrite the homepage H1 so a new visitor can identify the author, genre, books, or reader promise without relying on surrounding images. Keep it concise, specific, and rendered as semantic text rather than artwork or pseudo-content.",
    },
  },
  "search.indexability": {
    passed: {
      details: "The scan did not find an obvious robots or noindex signal blocking the inspected page from search engines.",
      recommendation: "Keep important public pages free of unintended `noindex`, `nofollow`, X-Robots-Tag, authentication, and robots.txt restrictions. After migrations, staging deployments, or SEO configuration changes, verify the live URL with a search-engine inspection tool.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Check robots.txt, page-level meta robots, X-Robots-Tag response headers, authentication, and canonical routing for the inspected URL. Remove accidental access barriers or expose the final public URL to the crawler, then verify it with a search-engine inspection tool and rerun the scan.",
    },
    failed: {
      details: "The scan found a noindex or similar signal that may keep the page out of search results.",
      recommendation: "Remove unintended `noindex` directives, X-Robots-Tag restrictions, robots.txt blocks, authentication, or environment settings from important public pages. Verify the deployed canonical URL with a search-engine inspection tool and request indexing after the fix.",
    },
  },
  "search.internal_links": {
    passed: {
      details: "The scan found useful internal links connecting visitors to important website content.",
      recommendation: "Maintain descriptive, crawlable internal links to Books, About, Contact, newsletter, and other priority pages using final canonical URLs. Run a link crawl after permalink or navigation changes to catch broken links, redirect chains, and orphaned destinations.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Follow the homepage's important links and inspect the rendered HTML for standard anchors to Books, About, Contact, newsletter, and other priority pages. Replace script-only navigation or blocked redirect links with crawlable final URLs before rescanning.",
    },
    failed: {
      details: "The scan did not find enough internal links to key author website pages.",
      recommendation: "Add descriptive internal anchors from the main navigation and relevant homepage sections to Books, About, Contact, newsletter, and other priority reader pages. Link directly to final canonical URLs and eliminate broken links or avoidable redirect chains.",
    },
  },
  "mobile.pagespeed_performance": {
    passed: {
      details: "PageSpeed reported a mobile performance score at or above the current target.",
      recommendation: "Protect the current mobile performance score by serving responsive compressed images, limiting render-blocking resources, deferring nonessential third-party code, and retaining effective page and browser caching. Rerun PageSpeed Insights after adding plugins, fonts, embeds, tracking scripts, or large media.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run PageSpeed Insights directly against the same public homepage URL and record whether a mobile result is returned. If the audit is blocked, remove authentication or challenge pages for legitimate testing, adjust WAF or consent behavior, and retry before rerunning the analyzer.",
    },
    failed: {
      details: "PageSpeed measured a mobile performance score below the target of 70.",
      recommendation: "Improve the mobile score to at least the configured target by resizing and compressing images, serving modern formats, reducing render-blocking CSS and JavaScript, deferring nonessential third-party code, and enabling effective caching. Use the individual PageSpeed diagnostics to prioritize the largest LCP, INP, CLS, and transfer-size contributors, then retest.",
    },
  },
  "mobile.pagespeed_accessibility": {
    passed: {
      details: "PageSpeed reported a mobile accessibility score at or above the current target.",
      recommendation: "Preserve accessible mobile behavior by maintaining sufficient contrast, programmatic labels, meaningful alternative text, logical focus order, and adequately sized touch targets. Retest with Lighthouse plus keyboard and screen-reader checks after changes to navigation, forms, dialogs, or interactive controls.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run a current mobile Lighthouse or PageSpeed accessibility audit and review the individual findings, not only the score. Ensure the public page can load without authentication, bot challenges, or an overlay that prevents Lighthouse from reaching the content.",
    },
    failed: {
      details: "PageSpeed measured a mobile accessibility score below the target of 90.",
      recommendation: "Resolve the failed mobile accessibility audits, prioritizing low contrast, missing accessible names, unlabeled form fields, incorrect alternative text, focus problems, and undersized or overlapping targets. Rerun Lighthouse and manually test keyboard and screen-reader behavior because the score alone does not confirm accessibility.",
    },
  },
  "mobile.text_contrast": {
    passed: {
      details: "Measured mobile text samples met the analyzer's baseline contrast requirement with sufficient coverage.",
      recommendation: "Keep text and controls above the required contrast ratio against their actual rendered backgrounds, including image overlays and hover, focus, disabled, and active states. Recalculate contrast whenever brand colors, transparency, background imagery, or button styles change.",
    },
    needs_review: {
      details: "The required rendered-page or viewport evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Measure representative mobile text, links, and controls against their actual rendered backgrounds with a contrast-testing tool. If the required viewport cannot render cleanly because of overlays, animation, or blocked assets, correct those rendering conditions and rescan.",
    },
    failed: {
      details: "The rendered mobile homepage contains measured text that falls below the baseline contrast threshold.",
      recommendation: "Adjust text, overlay, and background colors until each flagged mobile element meets the applicable WCAG contrast ratio in its normal and interactive states. Test the actual rendered combinations at mobile breakpoints, including text over images, transparent layers, links, and buttons.",
    },
  },
  "mobile.pagespeed_seo": {
    passed: {
      details: "PageSpeed reported a mobile SEO score at or above the current target.",
      recommendation: "Maintain complete mobile metadata, crawlable anchor links, valid status responses, and content that remains available in the rendered page without blocked resources. Review individual Lighthouse SEO audits after changes to routing, metadata generation, JavaScript rendering, or navigation.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run the mobile Lighthouse SEO audit on the exact public URL and inspect crawlability, metadata, status-code, and link findings. Resolve any access or rendering condition that prevents PageSpeed from returning a complete result, then rerun the analyzer.",
    },
    failed: {
      details: "PageSpeed measured a mobile search audit score below the target of 90.",
      recommendation: "Open the failed Lighthouse SEO audits and correct each reported crawlability, metadata, status-code, or link issue. Confirm that the public URL returns complete rendered metadata and crawlable anchors, then rerun the mobile audit.",
    },
  },
  "mobile.image_alt_text": {
    passed: {
      details: "The scan did not find the current missing-alt-text signal on inspected meaningful images.",
      recommendation: "Continue providing accurate `alt` attributes for meaningful images and empty `alt=\"\"` values for decorative images. Review newly uploaded book covers, portraits, banners, and linked graphics so their alternative text describes purpose without duplicating nearby text unnecessarily.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect meaningful images in the rendered DOM and verify that each has an appropriate `alt` attribute while decorative images use `alt=\"\"`. If images are supplied as CSS backgrounds or generated by a widget, add accessible equivalents or configure the component to expose alternative text.",
    },
    failed: {
      details: "The scan found images without alt text.",
      recommendation: "Add an `alt` attribute to every meaningful `<img>`, describing the image's purpose or content; identify covers by title and portraits by author name when that information is not already adjacent. Use `alt=\"\"` for decorative images so screen readers can ignore them.",
    },
  },
  "mobile.homepage_structure": {
    passed: {
      details: "The homepage loaded successfully and exposed a readable main heading to the scan.",
      recommendation: "Keep the public homepage returning a successful response and expose one visible text H1 in the initial rendered content without requiring login, consent, or user interaction. Retest in a signed-out mobile session after changes to popups, cookie tools, client-side rendering, or hero components.",
    },
    needs_review: {
      details: "The required rendered-page or viewport evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Load the homepage in a signed-out mobile browser and confirm that it returns successfully with one visible text H1 in the initial rendered content. Remove or reconfigure login gates, persistent overlays, or client-side failures that prevent the heading from being rendered, then rescan.",
    },
    failed: {
      details: "The homepage loaded, but the scan did not find a visible, readable main heading in the initial page content.",
      recommendation: "Ensure the homepage returns a successful public response and includes one visible text H1 in the initial rendered DOM. Remove persistent overlays or rendering errors that hide the heading, and verify the result in a signed-out mobile browser before rescanning.",
    },
  },
  "mobile.viewport_fit": {
    passed: {
      details: "The rendered mobile homepage showed no confirmed page-level horizontal overflow.",
      recommendation: "Preserve responsive sizing with fluid containers, wrapping text, scalable media, and constrained embeds so the document width never exceeds the viewport. Test common phone widths after adding sliders, forms, tables, iframes, badges, or fixed-position elements.",
    },
    needs_review: {
      details: "The required rendered-page or viewport evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Test the page at common phone widths and check whether the document itself scrolls horizontally or clips essential controls. If rendering evidence was incomplete, disable blocking overlays and inspect oversized fixed-width elements, transforms, tables, embeds, and sliders before rescanning.",
    },
    failed: {
      details: "The rendered mobile homepage contains page-level horizontal overflow that can cause sideways scrolling or clipped content.",
      recommendation: "Identify the element increasing the document width—commonly a fixed-width image, slider, form, iframe, table, transform, or absolutely positioned control—and replace rigid sizing with responsive constraints or wrapping. Confirm that `document.documentElement.scrollWidth` no longer exceeds the viewport at common phone widths.",
    },
  },
  "technical.desktop_performance": {
    passed: {
      details: "PageSpeed reported a desktop performance score at or above the current target.",
      recommendation: "Protect the current desktop performance result by optimizing image delivery, minimizing unused CSS and JavaScript, and retaining effective server, browser, and CDN caching. Rerun the desktop PageSpeed audit after major template, plugin, font, analytics, or media changes.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run PageSpeed Insights directly against the exact public URL in desktop mode and confirm that a complete performance result is returned. If the request is blocked by authentication, WAF rules, consent interstitials, or server errors, correct that access condition and retry the analyzer.",
    },
    failed: {
      details: "PageSpeed measured a desktop performance score below the target of 70.",
      recommendation: "Improve the desktop score to at least the configured target by serving appropriately sized modern images, removing unused CSS and JavaScript, reducing main-thread work, and configuring server, browser, or CDN caching. Use PageSpeed diagnostics to address the largest LCP, INP, CLS, and transfer-size contributors, then retest.",
    },
  },
  "technical.mobile_best_practices": {
    passed: {
      details: "PageSpeed reported a mobile best-practices score at or above the current target.",
      recommendation: "Maintain modern and secure mobile browser behavior by keeping dependencies current, eliminating console errors, avoiding mixed content, and using safe APIs and embeds. Review the individual Lighthouse best-practices audits after updating plugins, scripts, analytics, or third-party widgets.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run the mobile Lighthouse best-practices audit and inspect console, security, image, and browser-API findings. Ensure the page and its required resources are available to Lighthouse without a bot challenge or persistent overlay, then rerun the analyzer.",
    },
    failed: {
      details: "PageSpeed measured a mobile best-practices score below the target of 90.",
      recommendation: "Resolve every failed mobile best-practices audit, including console errors, insecure resource requests, deprecated APIs, image-delivery problems, and outdated libraries or embeds. Test the deployed page in the browser console and rerun Lighthouse after the fixes.",
    },
  },
  "technical.desktop_best_practices": {
    passed: {
      details: "PageSpeed reported a desktop best-practices score at or above the current target.",
      recommendation: "Keep desktop integrations free of console errors, insecure requests, deprecated browser APIs, and outdated dependencies. Validate the deployed page with a fresh Lighthouse best-practices run whenever frontend libraries, embeds, or tracking tools change.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run the desktop Lighthouse best-practices audit on the public URL and review every incomplete or failed audit. Resolve access restrictions, resource failures, or rendering errors that prevent a complete result before rescanning.",
    },
    failed: {
      details: "PageSpeed measured a desktop best-practices score below the target of 90.",
      recommendation: "Correct all failed desktop best-practices findings, prioritizing console errors, mixed content, deprecated APIs, unsafe browser behavior, and outdated third-party integrations. Deploy the fixes and verify the exact public URL with a fresh Lighthouse audit.",
    },
  },
  "technical.desktop_accessibility": {
    passed: {
      details: "PageSpeed reported a desktop accessibility score at or above the current target.",
      recommendation: "Preserve desktop accessibility by maintaining semantic headings, descriptive link and control names, form labels, visible focus indicators, sufficient contrast, and full keyboard operation. Pair automated audits with manual keyboard testing after changes to menus, forms, templates, or interactive components.",
    },
    needs_review: {
      details: "The required PageSpeed result was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Run a current desktop accessibility audit and manually test keyboard focus, form labels, link names, and dialog behavior. If PageSpeed cannot inspect the page, remove the authentication, challenge, or blocking layer responsible and rerun the analyzer.",
    },
    failed: {
      details: "PageSpeed measured a desktop accessibility score below the target of 90.",
      recommendation: "Fix the highest-impact desktop accessibility findings, including contrast, form labels, accessible names, heading order, focus visibility, and keyboard operation. Rerun automated checks and complete a manual keyboard pass to confirm that interactive content remains usable.",
    },
  },
  "technical.https": {
    passed: {
      details: "The inspected homepage uses an HTTPS address.",
      recommendation: "Keep a valid TLS certificate installed for every public hostname, force permanent HTTP-to-HTTPS redirects, and load all page assets over HTTPS. Monitor certificate renewal and check for mixed-content or redirect errors after hosting, CDN, proxy, or domain changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the homepage and key public URLs and inspect the certificate chain, browser security indicator, redirects, and mixed-content console warnings. Correct expired certificates, hostname mismatches, HTTP endpoints, or inaccessible final URLs before rescanning.",
    },
    failed: {
      details: "The scanned homepage did not use a secure HTTPS address.",
      recommendation: "Install or renew a valid TLS certificate for every public hostname, configure permanent HTTP-to-HTTPS redirects, and update internal links and assets to secure URLs. Check the browser console for mixed content and verify the certificate chain and hostname coverage.",
    },
  },
  "technical.page_responses": {
    passed: {
      details: "The homepage and inspected pages returned successful responses under this technical-health check.",
      recommendation: "Keep each reader-facing URL returning the intended successful response and link directly to its final canonical destination. Run a crawl after permalink, navigation, hosting, or content-removal changes to catch 4xx/5xx responses and unnecessary redirect chains.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open every URL recorded by the scan and capture its final HTTP status, redirect chain, and rendered page. Restore inaccessible pages, correct server errors, or point the scanner and internal links to the final public URL, then rerun the crawl.",
    },
    failed: {
      details: "The scan confirmed that at least one inspected URL returned a non-success response or an avoidable redirect chain.",
      recommendation: "Repair every inspected URL returning a 4xx or 5xx response and replace unnecessary redirect chains with direct links to the final page. Restore required content or configure appropriate permanent redirects, then run a fresh crawl to confirm successful responses.",
    },
  },
  "technical.indexability": {
    passed: {
      details: "The technical scan did not find an obvious indexing block on the inspected public content.",
      recommendation: "Preserve crawler access to important public pages by keeping robots.txt, meta robots directives, and X-Robots-Tag headers aligned with indexing intent. Verify the live homepage and priority pages after deployments, SEO-plugin changes, or staging-to-production migrations.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect robots.txt, meta robots tags, X-Robots-Tag headers, authentication, and response status for the homepage and priority pages. Remove unintended crawler restrictions or provide the scanner with the correct final public URL before rescanning.",
    },
    failed: {
      details: "The scan found a robots rule, response directive, or page-level noindex signal that blocks important public content from search engines.",
      recommendation: "Remove confirmed robots.txt blocks, meta robots directives, X-Robots-Tag headers, authentication, or environment restrictions from public pages intended for search. Verify the live URL with a search-engine inspection tool and confirm that the canonical destination is crawlable.",
    },
  },
  "technical.canonical_or_schema": {
    passed: {
      details: "The scan found a canonical URL or relevant Person or Organization structured data.",
      recommendation: "Keep canonical tags self-referencing and consistent with the preferred public URL, and maintain accurate Person or Organization structured data with stable identity fields. Validate the rendered markup after domain, author-name, SEO-plugin, or template changes to catch conflicts and syntax errors.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the rendered `<head>` for a valid canonical link and the page source for parsable Person or Organization JSON-LD. If markup is inserted only after unsupported interaction or is malformed, correct the output and validate it before rerunning the analyzer.",
    },
    failed: {
      details: "The scan did not find a canonical URL or basic author/site structured data.",
      recommendation: "Add a self-referencing canonical link to each important indexable page and publish valid Person or Organization JSON-LD with a consistent author name, URL, and official profiles. Validate the live rendered markup and remove duplicate, malformed, or conflicting identity data.",
    },
  },
  "trust.author_bio": {
    passed: {
      details: "The scan found author-biography content in the inspected website pages.",
      recommendation: "Keep the author biography current, specific, and available as readable HTML on an accessible About page, with a concise homepage summary where appropriate. Update titles, publications, awards, representation, credentials, and contact references when they change.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the public About page or biography section and confirm that substantive author information is present as readable HTML. If the bio is hidden behind a tab, image, login, or client-side failure, expose a default accessible version and rescan.",
    },
    failed: {
      details: "The scan did not find a clear author bio or biography page.",
      recommendation: "Publish a substantive author biography as readable HTML on a public About page and add a concise homepage summary. Include genre, notable work, and relevant credentials, and keep the text current for readers, press, and event organizers.",
    },
  },
  "trust.author_photo": {
    passed: {
      details: "The scan found an image signal consistent with a visible author photo.",
      recommendation: "Continue serving a current portrait as a responsive image with appropriate dimensions, compression, and alt text identifying the author when the image conveys identity. Check crop, sharpness, and focal positioning across mobile and desktop layouts after replacing the photo.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Confirm that a recognizable author portrait is visible on the public homepage or About page and represented by an accessible image element with useful alt text. If the image is lazy-loaded only after interaction or rendered as an inaccessible background, correct the component and rerun the scan.",
    },
    failed: {
      details: "The scan did not find an author photo, portrait, or headshot signal.",
      recommendation: "Add a current high-resolution author portrait to the About page or homepage trust section using a responsive image element. Supply appropriate dimensions, compression, and alt text identifying the author, and verify the crop at desktop and mobile widths.",
    },
  },
  "trust.contact_path": {
    passed: {
      details: "The scan found a contact form, email path, or clearly identified contact destination.",
      recommendation: "Keep the Contact page linked with a direct crawlable URL and ensure the form or email destination reaches a monitored inbox. Test required fields, validation, spam protection, confirmation messaging, email delivery, and accessibility after form or hosting changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Follow the Contact link, confirm a direct successful page response, and test the form or email path through completion. Correct broken routes, inaccessible embedded forms, bot challenges, or script failures that prevent the scanner from reaching the contact destination.",
    },
    failed: {
      details: "The scan did not find a contact form or contact email.",
      recommendation: "Create a clearly labeled Contact page with a working accessible form or purpose-specific email address. Configure validation, spam protection, success messaging, and inbox delivery, then submit a test message to verify the complete path.",
    },
  },
  "trust.social_profiles": {
    passed: {
      details: "The scan found links to one or more social profiles.",
      recommendation: "Keep only active official profiles and expose them as descriptive links with correct destinations and accessible names. Test each URL after username, platform, icon library, or footer changes, and remove abandoned accounts.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open each visible social link and confirm that it is a standard anchor leading to the author's active official profile. Replace icon-only controls without accessible names, JavaScript-only navigation, or blocked redirectors, then rescan.",
    },
    failed: {
      details: "The scan did not find links to author social profiles.",
      recommendation: "Add standard links to the author's active official social profiles in a consistent header, footer, or contact area. Give icon-only links accessible names, use final profile URLs, and remove abandoned or unrelated accounts.",
    },
  },
  "trust.media_kit": {
    passed: {
      details: "The scan found a media-kit or press-resource signal in the inspected website content.",
      recommendation: "Keep the media kit reachable from About or Contact and maintain current downloadable bios, headshots, covers, book data, usage notes, and press contact information. Verify file permissions, file sizes, and direct download links after every release or asset update.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the media or press path and confirm that biographies, book information, downloadable assets, and contact details are publicly reachable. Repair broken file permissions, inaccessible cloud links, or unlinked pages before rerunning the scan.",
    },
    failed: {
      details: "The scan did not find a media kit, press kit, or press page.",
      recommendation: "Create a public media page containing approved short and long biographies, high-resolution headshots, cover files, book information, usage notes, and press contact details. Use stable downloadable URLs with correct permissions and link the page from About or Contact.",
    },
  },
  "trust.privacy_policy": {
    passed: {
      details: "The scan found a privacy-policy page or link.",
      recommendation: "Keep the privacy policy publicly accessible and aligned with the site's actual forms, newsletter provider, analytics, cookies, embeds, and data-retention practices. Review the policy and nearby consent disclosures whenever a data-collection or marketing integration changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open the Privacy link from the footer and relevant forms and confirm that the policy returns a successful public page with current text. Fix broken routes, authentication, empty policy templates, or inaccessible embedded documents before rescanning.",
    },
    failed: {
      details: "The scan did not find a visible privacy-policy link.",
      recommendation: "Publish a privacy policy that accurately reflects the site's forms, newsletter provider, analytics, cookies, embeds, data uses, retention, and user choices. Link it persistently from the footer and near relevant data-collection forms, and have the wording reviewed for the jurisdictions served.",
    },
  },
  "trust.reader_proof": {
    passed: {
      details: "The scan found credibility proof such as praise, reviews, awards, ratings, or related structured data.",
      recommendation: "Maintain credible trust proof with clear attribution and enough context for visitors to understand the source. Check quoted wording, ratings, awards, and source links periodically, and remove unsupported or outdated claims.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect visible reviews, praise, awards, and ratings and confirm that each includes a credible source or enough supporting context. If proof is loaded only through a blocked widget or hidden interaction, add a readable attributed version to the page and rescan.",
    },
    failed: {
      details: "The scan did not find reviews, praise, ratings, or similar trust proof.",
      recommendation: "Add credible, attributable reviews, awards, ratings, endorsements, or reader testimonials near the author bio or featured book. Include enough source context to support each claim and link to evidence when useful.",
    },
  },
  "usability.primary_navigation": {
    passed: {
      details: "The rendered homepage provided usable primary navigation across every required viewport.",
      recommendation: "Preserve a semantic, keyboard-accessible primary navigation with a visible desktop menu and an operable mobile menu button that exposes priority links. Test focus order, expanded state, escape behavior, link targets, and viewport transitions after theme or menu changes.",
    },
    needs_review: {
      details: "The required rendered-page or viewport evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Operate the primary navigation at desktop, tablet, and mobile widths using both pointer and keyboard input. Correct missing menu controls, focus traps, hidden links, viewport-specific rendering failures, or overlays that prevent the scanner from capturing a usable menu.",
    },
    failed: {
      details: "The rendered homepage did not provide usable primary navigation in every tested viewport.",
      recommendation: "Implement a semantic primary navigation with a visible desktop menu and an accessible mobile menu button that communicates its expanded state. Ensure Books, About, Newsletter, and Contact remain reachable by keyboard and pointer at desktop, tablet, and mobile widths.",
    },
  },
  "usability.page_responses": {
    passed: {
      details: "The pages inspected for site usability returned successful responses.",
      recommendation: "Keep all usability-critical reader paths returning successful responses and linking directly to their final destinations. Perform a focused crawl of navigation, homepage calls to action, book links, contact routes, and footer links after structural changes.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Open each reader-facing path recorded for the usability scan and verify a direct successful response without unnecessary redirects. Repair unavailable routes or update internal links to the final public destinations before rerunning the scan.",
    },
    failed: {
      details: "At least one scanned page did not return a successful response.",
      recommendation: "Repair each unsuccessful reader-facing URL and update menus, homepage calls to action, and content links to point directly to working final destinations. Remove avoidable redirect chains and verify the full reader path with a fresh crawl.",
    },
  },
  "usability.privacy_policy": {
    passed: {
      details: "The scan found a privacy-policy path available to website visitors.",
      recommendation: "Keep the Privacy link persistent in the footer and available near forms where users submit personal information. Confirm that the destination loads without authentication and that form disclosures remain consistent after theme or form-builder updates.",
    },
    needs_review: {
      details: "The required crawl or page-response evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Use the public footer and forms to confirm that visitors can reach the Privacy page through a standard link. Restore a missing link, correct the destination, or expose the policy without login or script-only navigation, then rescan.",
    },
    failed: {
      details: "The scan did not find a privacy-policy link, creating a maintenance and trust concern for forms and newsletter collection.",
      recommendation: "Publish or update a privacy policy that matches the site's current forms, analytics, cookies, embeds, and email tools, then add a persistent footer link and appropriate form disclosures. Confirm that the policy URL is public, stable, and returns a successful response.",
    },
  },
  "usability.canonical_or_schema": {
    passed: {
      details: "The scan found canonical or structured identity markup that supports consistent site interpretation.",
      recommendation: "Keep the canonical URL and author identity markup synchronized with the preferred hostname, protocol, page URL, and public author name. Validate rendered canonical and structured-data output after template, domain, routing, or SEO-plugin changes.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Inspect the final rendered canonical URL and Person or Organization markup and compare their name, hostname, protocol, and page identity. Correct malformed, conflicting, or client-only markup and validate the live page before rerunning the analyzer.",
    },
    failed: {
      details: "The scan did not find a canonical URL or basic site/author structured data.",
      recommendation: "Add self-referencing canonical tags and accurate Person or Organization structured data to the homepage and other important public pages. Keep protocol, hostname, URL, author name, and official-profile references consistent, then validate the live markup.",
    },
  },
  "usability.freshness": {
    passed: {
      details: "The scan found a current-enough freshness signal in the inspected website content.",
      recommendation: "Maintain current book availability, release information, event dates, biography details, contact information, and external links rather than relying on the copyright year alone. Establish a scheduled editorial review and update visible timestamps only when the associated content has genuinely changed.",
    },
    needs_review: {
      details: "The required website content or markup evidence was unavailable or incomplete, so the analyzer could not reliably determine whether this check passes.",
      recommendation: "Review visible dates, book availability, event listings, biography details, contact information, and external links rather than relying only on the footer year. If current content is hidden from the scanner by interaction-dependent components, expose the relevant text in the default rendered page and rescan.",
    },
    failed: {
      details: "The scan found a footer copyright year that appears several years out of date.",
      recommendation: "Update stale copyright, book-availability, event, biography, contact, and external-link information based on the actual content state. Add a scheduled editorial review process; an automatically changing footer year should not substitute for reviewing substantive content.",
    },
  },
} as const satisfies Record<
  ScoringCheckId,
  Record<AuditCheckStatus, AuditCheckStatusContent>
>;

export function getCheckStatusContent(
  checkId: ScoringCheckId,
  status: AuditCheckStatus,
): AuditCheckStatusContent {
  return CHECK_STATUS_CONTENT[checkId][status];
}
