import PDFDocument from "pdfkit";

import { FindingSeverity, ReportCategory } from "@/generated/prisma/client";
import type { ReportNarrative } from "@/lib/ai/report-narrative.core";

export type PdfReport = {
  id: string;
  normalizedUrl: string;
  domain: string;
  overallScore: number | null;
  createdAt: Date;
  completedAt: Date | null;
};

export type PdfReportScore = {
  category: ReportCategory;
  score: number;
  maxScore: number;
  summary: string | null;
};

export type PdfReportFinding = {
  category: ReportCategory;
  severity: FindingSeverity;
  checkId?: string | null;
  title: string;
  finding: string;
  recommendation: string;
  priority: number;
};

export type AuthorReportPdfInput = {
  report: PdfReport;
  scores: PdfReportScore[];
  findings: PdfReportFinding[];
  narrative: ReportNarrative | null;
  executiveSummary: string;
  generatedAt: Date;
};

const categoryOrder = [
  ReportCategory.BRAND_CLARITY,
  ReportCategory.BOOK_VISIBILITY,
  ReportCategory.READER_ENGAGEMENT,
  ReportCategory.SEARCH_VISIBILITY,
  ReportCategory.MOBILE_PERFORMANCE,
  ReportCategory.TECHNICAL_HEALTH,
  ReportCategory.AUTHOR_TRUST,
  ReportCategory.SITE_USABILITY,
];

const categoryLabels: Record<ReportCategory, string> = {
  BRAND_CLARITY: "Brand Clarity",
  BOOK_VISIBILITY: "Book Visibility",
  READER_ENGAGEMENT: "Reader Engagement",
  SEARCH_VISIBILITY: "Search Visibility",
  MOBILE_PERFORMANCE: "Mobile Performance",
  TECHNICAL_HEALTH: "Technical Health",
  AUTHOR_TRUST: "Author Trust",
  SITE_USABILITY: "Site Usability",
};

export function getAuthorReportPdfFileName(domain: string) {
  const safeDomain =
    domain
      .toLowerCase()
      .replace(/[^a-z0-9.-]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "author-website-report";

  return `${safeDomain}-author-website-report.pdf`;
}

const severityLabels: Record<FindingSeverity, string> = {
  LOW: "Low",
  MEDIUM: "Medium",
  HIGH: "High",
  CRITICAL: "Critical",
};

const PAGE_MARGIN = 54;
const BRAND = "#111827";
const MUTED = "#4b5563";
const BORDER = "#d1d5db";
const ACCENT = "#2563eb";

function formatDate(value: Date) {
  return new Intl.DateTimeFormat("en", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(value);
}

function scorePercent(score: number, maxScore: number) {
  if (maxScore <= 0) {
    return 0;
  }

  return Math.round((score / maxScore) * 100);
}

function severityWeight(severity: FindingSeverity) {
  if (severity === FindingSeverity.CRITICAL) {
    return 4;
  }

  if (severity === FindingSeverity.HIGH) {
    return 3;
  }

  if (severity === FindingSeverity.MEDIUM) {
    return 2;
  }

  return 1;
}

function scoreInterpretation(score: number | null) {
  if (score === null) {
    return "Not scored";
  }

  if (score >= 90) {
    return "Strong";
  }

  if (score >= 75) {
    return "Good foundation";
  }

  if (score >= 60) {
    return "Needs improvement";
  }

  if (score >= 40) {
    return "Weak";
  }

  return "Needs major attention";
}

function collectPdfBuffer(doc: PDFKit.PDFDocument) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function pageWidth(doc: PDFKit.PDFDocument) {
  return doc.page.width - PAGE_MARGIN * 2;
}

function ensureSpace(doc: PDFKit.PDFDocument, height: number) {
  if (doc.y + height > doc.page.height - PAGE_MARGIN) {
    doc.addPage();
  }
}

function addFooter(doc: PDFKit.PDFDocument) {
  const bottom = doc.page.height - 34;

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#6b7280")
    .text(
      "Generated by GrailHiiv Author Website Analyzer.",
      PAGE_MARGIN,
      bottom,
      {
        width: pageWidth(doc),
        align: "center",
      },
    );
}

function sectionTitle(doc: PDFKit.PDFDocument, title: string) {
  ensureSpace(doc, 42);
  doc.moveDown(0.8);
  doc
    .font("Helvetica-Bold")
    .fontSize(15)
    .fillColor(BRAND)
    .text(title, PAGE_MARGIN, doc.y, { width: pageWidth(doc) });
  doc.moveDown(0.35);
}

function paragraph(doc: PDFKit.PDFDocument, text: string) {
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(MUTED)
    .text(text, PAGE_MARGIN, doc.y, {
      width: pageWidth(doc),
      lineGap: 3,
    });
  doc.moveDown(0.55);
}

function keyValue(doc: PDFKit.PDFDocument, label: string, value: string) {
  const y = doc.y;
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(BRAND)
    .text(label, PAGE_MARGIN, y, {
      width: 120,
    });
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(MUTED)
    .text(value, PAGE_MARGIN + 130, y, {
      width: pageWidth(doc) - 130,
    });
  doc.moveDown(0.45);
}

function scoreBar(
  doc: PDFKit.PDFDocument,
  label: string,
  score: number,
  maxScore: number,
) {
  ensureSpace(doc, 32);

  const width = pageWidth(doc);
  const percent = scorePercent(score, maxScore);
  const y = doc.y;

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(BRAND)
    .text(label, PAGE_MARGIN, y, { width: width - 70 });
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(MUTED)
    .text(`${score}/${maxScore}`, PAGE_MARGIN + width - 65, y, {
      width: 65,
      align: "right",
    });

  const barY = doc.y + 5;
  doc.roundedRect(PAGE_MARGIN, barY, width, 7, 3).fill("#e5e7eb");
  doc
    .roundedRect(PAGE_MARGIN, barY, (width * percent) / 100, 7, 3)
    .fill(ACCENT);
  doc.y = barY + 16;
}

function findingBlock(
  doc: PDFKit.PDFDocument,
  finding: PdfReportFinding,
  includeCategory = false,
) {
  ensureSpace(doc, 78);

  const title = includeCategory
    ? `${finding.title} (${categoryLabels[finding.category]})`
    : finding.title;

  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(BRAND)
    .text(title, PAGE_MARGIN, doc.y, { width: pageWidth(doc) });
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#6b7280")
    .text(`${severityLabels[finding.severity]} priority`, PAGE_MARGIN, doc.y, {
      width: pageWidth(doc),
    });
  doc.moveDown(0.25);
  paragraph(doc, finding.finding);
  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(BRAND)
    .text("Recommendation", {
      continued: false,
    });
  paragraph(doc, finding.recommendation);
  doc.moveDown(0.1);
}

function recommendationPlanBlock(
  doc: PDFKit.PDFDocument,
  finding: PdfReportFinding,
  position: number,
) {
  ensureSpace(doc, 58);
  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(BRAND)
    .text(
      `${position}. ${recommendationPlanTitle(finding.checkId, finding.title)}`,
      PAGE_MARGIN,
      doc.y,
      {
        width: pageWidth(doc),
      },
    );
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#6b7280")
    .text(
      `${categoryLabels[finding.category]} - ${severityLabels[finding.severity]} priority`,
      PAGE_MARGIN,
      doc.y,
      { width: pageWidth(doc) },
    );
  doc.moveDown(0.25);
  paragraph(doc, finding.recommendation);
}

function recommendationPlanTitle(
  checkId: string | null | undefined,
  fallback: string,
) {
  const titles: Record<string, string> = {
    "usability.primary_navigation": "Make navigation work on every screen",
    "mobile.pagespeed_performance": "Speed up the homepage on mobile",
    "engagement.reader_magnet": "Give readers a reason to subscribe",
    "engagement.subscriber_benefit":
      "Explain what newsletter subscribers will receive",
    "mobile.image_alt_text": "Add alt text to important images",
  };

  return (checkId ? titles[checkId] : undefined) ?? fallback;
}

function addHeader(doc: PDFKit.PDFDocument, input: AuthorReportPdfInput) {
  doc.rect(0, 0, doc.page.width, 96).fill("#f9fafb");
  doc
    .font("Helvetica-Bold")
    .fontSize(18)
    .fillColor(BRAND)
    .text("GrailHiiv Author Website Analyzer", PAGE_MARGIN, 30, {
      width: pageWidth(doc),
    });
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor(MUTED)
    .text("Author Website Report", PAGE_MARGIN, 56, {
      width: pageWidth(doc),
    });
  doc.y = 120;

  const score = input.report.overallScore;
  const scoreText = score === null ? "--" : String(score);

  doc
    .font("Helvetica-Bold")
    .fontSize(46)
    .fillColor(BRAND)
    .text(scoreText, PAGE_MARGIN, doc.y, { continued: true });
  doc.font("Helvetica").fontSize(16).fillColor(MUTED).text(" /100");
  doc.moveDown(0.2);
  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(ACCENT)
    .text(scoreInterpretation(score), PAGE_MARGIN, doc.y, {
      width: pageWidth(doc),
    });
  doc.moveDown(1);

  keyValue(doc, "Website", input.report.normalizedUrl);
  keyValue(
    doc,
    "Report date",
    formatDate(input.report.completedAt ?? input.report.createdAt),
  );
  keyValue(doc, "Date generated", formatDate(input.generatedAt));
}

export async function renderAuthorReportPdf(input: AuthorReportPdfInput) {
  const doc = new PDFDocument({
    autoFirstPage: false,
    margin: PAGE_MARGIN,
    size: "LETTER",
    bufferPages: true,
    info: {
      Title: `Author Website Report - ${input.report.domain}`,
      Author: "GrailHiiv",
      Subject: "Author Website Report",
      Creator: "GrailHiiv Author Website Analyzer",
    },
  });
  const pdfBuffer = collectPdfBuffer(doc);

  doc.addPage();
  addHeader(doc, input);

  sectionTitle(doc, "What to Focus on First");
  paragraph(doc, input.executiveSummary);

  sectionTitle(doc, "Category Scores");
  paragraph(
    doc,
    "These eight scores show where the website supports readers well and where focused improvements will have the most impact.",
  );
  const scoresByCategory = new Map(
    input.scores.map((score) => [score.category, score]),
  );

  for (const category of categoryOrder) {
    const score = scoresByCategory.get(category);

    if (score) {
      scoreBar(doc, categoryLabels[category], score.score, score.maxScore);
    }
  }

  sectionTitle(doc, "Priority Recommendations");
  paragraph(
    doc,
    "Start with these three recommendations in priority order. Complete evidence follows in the category findings.",
  );
  const topFindings = [...input.findings]
    .sort(
      (a, b) =>
        a.priority - b.priority ||
        severityWeight(b.severity) - severityWeight(a.severity) ||
        a.title.localeCompare(b.title),
    )
    .slice(0, 3);

  if (topFindings.length > 0) {
    topFindings.forEach((finding, index) =>
      recommendationPlanBlock(doc, finding, index + 1),
    );
  } else {
    paragraph(doc, "No priority fixes were saved with this report.");
  }

  sectionTitle(doc, "Findings by Category");
  paragraph(
    doc,
    "Review every issue and recommendation, grouped by score category.",
  );
  for (const category of categoryOrder) {
    const relatedFindings = input.findings.filter(
      (finding) => finding.category === category,
    );
    const score = scoresByCategory.get(category);

    if (!score && relatedFindings.length === 0) {
      continue;
    }

    ensureSpace(doc, 60);
    doc
      .font("Helvetica-Bold")
      .fontSize(12)
      .fillColor(BRAND)
      .text(categoryLabels[category], PAGE_MARGIN, doc.y, {
        width: pageWidth(doc),
      });

    relatedFindings.forEach((finding) => {
      findingBlock(doc, finding);
    });
  }

  ensureSpace(doc, 74);
  doc
    .roundedRect(PAGE_MARGIN, doc.y, pageWidth(doc), 64, 8)
    .strokeColor(BORDER)
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.8);
  doc
    .font("Helvetica-Bold")
    .fontSize(12)
    .fillColor(BRAND)
    .text(
      "Want help turning this report into a plan?",
      PAGE_MARGIN + 16,
      doc.y,
      {
        width: pageWidth(doc) - 32,
      },
    );
  doc.moveDown(0.25);
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(MUTED)
    .text(
      "GrailHiiv can review the priority issues with you and recommend the best next steps for your author website.",
      PAGE_MARGIN + 16,
      doc.y,
      { width: pageWidth(doc) - 32, lineGap: 2 },
    );

  const range = doc.bufferedPageRange();

  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    addFooter(doc);
  }

  doc.end();

  return pdfBuffer;
}
